version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  fail_on_warning: true
